import type { Post } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home = () => {
  return <PostsView />;
};

const PostsView = () => {
  const posts = api.posts.getAll.useQuery();

  if (posts.isLoading) return <div>Loading...</div>;

  const data = posts.data;

  if (posts.isError || !data) return <div>Error: {posts.error.message}</div>;

  return (
    <div className="flex h-screen w-screen justify-center">
      <div className="flex w-full max-w-5xl flex-col items-center  bg-slate-50">
        {[...data, ...data].map((post) => (
          <PostItem key={post.id} post={post} />
        ))}
      </div>
    </div>
  );
};

const PostItem = (props: { post: Post }) => {
  const post = props.post;

  return (
    <div className="w-full border-b border-slate-200 p-4 text-teal-400">
      {post.content}
    </div>
  );
};

const App: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
};

export default App;
