import type { Post } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home = () => {
  return (
    <div className="flex h-screen w-screen justify-center ">
      <div className="w-full max-w-3xl items-center border-x-2">
        <CreatePost />
        <PostsView />
      </div>
    </div>
  );
};

const CreatePost = () => {
  return (
    <div className="my-2 flex w-full flex-row border-b-4 p-2">
      <textarea
        // dont show border when focused
        className=" w-full resize-none rounded-xl py-2 outline-none"
        maxLength={140}
      />
      <button className=" h-14 rounded-xl bg-teal-400 px-8   text-white">
        Post
      </button>
    </div>
  );
};

const PostsView = () => {
  const posts = api.posts.getAll.useQuery();

  if (posts.isLoading) return <div>Loading...</div>;

  const data = posts.data;

  if (posts.isError || !data) return <div>Error: {posts.error.message}</div>;

  return (
    <div className="flex flex-col ">
      {[...data, ...data].map((post) => (
        <PostItem key={post.id} post={post} />
      ))}
    </div>
  );
};

const PostItem = (props: { post: Post }) => {
  const post = props.post;

  return <div className="w-full border-b  p-4">{post.content}</div>;
};

const App: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
};

export default App;
