import type { Post } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

import { type SubmitHandler, useForm } from "react-hook-form";
import { MutableRefObject, forwardRef, useRef } from "react";
import InfiniteScroll from "react-infinite-scroll-component";

const Home = () => {
  return (
    <div className="flex h-screen w-screen justify-center ">
      <div className="w-full max-w-3xl items-center border-x-2">
        <CreatePost />
        <PostsView />
      </div>
    </div>
  );
};

type FormValues = {
  content: string;
};

const CreatePost = () => {
  const { register, reset: resetForm, handleSubmit } = useForm<FormValues>();

  const ctx = api.useContext();

  const { mutate, isLoading: isPosting } = api.posts.create.useMutation({
    onSuccess: () => {
      resetForm({
        content: "",
      });
      void ctx.posts.getAll.invalidate();
    },
  });

  const createPost: SubmitHandler<FormValues> = (vals) => {
    const cont = vals.content;
    mutate({ content: cont });
  };

  return (
    <form
      onSubmit={(event) => {
        void handleSubmit(createPost)(event);
      }}
    >
      <div className="my-2 flex w-full flex-row border-b-4 p-2">
        <textarea
          // dont show border when focused
          className=" w-full resize-none rounded-xl py-2 outline-none"
          maxLength={140}
          placeholder="What's happening?"
          {...register("content", { required: true })}
        />
        {isPosting && <div>Posting...</div>}
        {!isPosting && (
          <button
            className="h-14 rounded-xl bg-teal-400 px-8 text-white"
            type="submit"
          >
            Post
          </button>
        )}
      </div>
    </form>
  );
};

const PostsView = () => {
  const { data, fetchNextPage, isLoading, isError, error, hasNextPage } =
    api.posts.getAll.useInfiniteQuery(
      {},
      {
        getNextPageParam: (lastPage) => lastPage.nextCursor,
      }
    );

  if (isLoading) return <div>Loading...</div>;

  if (isError || !data) return <div>Error: {error?.message}</div>;

  const posts = data.pages.flatMap((page) => page.items);

  return (
    <>
      <InfiniteScroll
        dataLength={posts.length}
        next={fetchNextPage}
        hasMore={hasNextPage == true}
        loader={<h4>Loading...</h4>}
      >
        {/* <div className="flex flex-col "> */}
        {...posts.map((post) => <PostItem key={post.id} post={post} />)}
        {/* </div> */}
      </InfiniteScroll>
    </>
  );
};

const PostItem = (props: { post: Post }) => {
  const post = props.post;

  return <div className="w-full border-b p-4">{post.content}</div>;
};

const App: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
};

export default App;
